### ISSUE TITLE
Bug with CHILD_SA net{1} selected proposal

### ISSUE THREAD

**Issue by shivang2121** [strongX509/docker#10]
Why is the selected proposal for the CHILD_SA 1 (net) the following?

04[CFG] selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/NO_EXT_SEQ
04[IKE] CHILD_SA net{1} established with SPIs cd5c1aef_i cb0c1fd9_o and TS 10.3.0.1/32 === 10.1.0.0/24

The rekeying of first Child SA fixes this : 
12[CFG] selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/CURVE_25519/NO_EXT_SEQ/KE1_KYBER_L3/KE2_BIKE_L3/KE3_HQC_L3

Again, the proposal from Carol is : 
net {
            remote_ts = 10.1.0.0/16
            esp_proposals = aes256-sha256-x25519-ke1_kyber3-ke2_bike3-ke3_hqc3
            rekey_time = 20m
          }

**Comment by strongX509** [comment]
When the first CHILD_SA is created as part of the IKE_AUTH message pair, the ESP session keys are derived from the key exchange of the IKE_SA. Thus 
````
04[CFG] selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/NO_EXT_SEQ
04[IKE] CHILD_SA net{1} established with SPIs cd5c1aef_i cb0c1fd9_o and TS 10.3.0.1/32 === 10.1.0.0/24
````
is shown without any KE algorithms. Only after the first rekeying where the CREATE_CHILD_SA does a fresh key exchange, the KE algorithms used are displayed:
````
12[CFG] selected proposal ESP:AES_CBC_256/HMAC_SHA2_256_128/CURVE_25519/NO_EXT_SEQ/KE1_KYBER_L3/KE2_BIKE_L3/KE3_HQC_L3
````
